using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client.UserInterface.Systems.Chat.Controls.Denu.Components;

[GenerateTypedNameReferences]
public sealed partial class ScopeSelector : BoxContainer
{
    public event Action<bool>? OnScopeChanged;

    public ScopeSelector()
    {
        RobustXamlLoader.Load(this);

        var group = new ButtonGroup();
        GlobalButton.Group = group;
        CharacterButton.Group = group;

        GlobalButton.OnPressed += _ => OnScopeChanged?.Invoke(true);
        CharacterButton.OnPressed += _ => OnScopeChanged?.Invoke(false);
    }

    public void SetScope(bool global)
    {
        GlobalButton.Pressed = global;
        CharacterButton.Pressed = !global;
    }

    public void SetEntity(EntityUid? entity)
    {
        PlayerSprite.SetEntity(entity);
    }
}
